# Generated by Django 3.0.3 on 2020-06-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20200611_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='cemail',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
